package com.example.zwj.recyclerviewdemo;

/**
 * Created by zwj on 16/4/27.
 */
public class DATAS {
    public static final int[] ICONS = new int[]{
            R.mipmap.img_01,
            R.mipmap.img_02,
            R.mipmap.img_03,
            R.mipmap.img_04,
            R.mipmap.img_05,
            R.mipmap.img_06,
            R.mipmap.img_07,
            R.mipmap.img_08,
            R.mipmap.img_09,
            R.mipmap.img_010,
            R.mipmap.img_11,
            R.mipmap.img_01,
            R.mipmap.img_02,
            R.mipmap.img_03,
            R.mipmap.img_04,
            R.mipmap.img_05,
            R.mipmap.img_06,
            R.mipmap.img_07,
            R.mipmap.img_08,
            R.mipmap.img_09,
            R.mipmap.img_010,
            R.mipmap.img_11,
            R.mipmap.img_01,
            R.mipmap.img_02,
            R.mipmap.img_03,
            R.mipmap.img_04,
            R.mipmap.img_05,
            R.mipmap.img_06,
            R.mipmap.img_07,
            R.mipmap.img_08,
            R.mipmap.img_09,
            R.mipmap.img_010,
            R.mipmap.img_11,
            R.mipmap.img_01,
            R.mipmap.img_02,
            R.mipmap.img_03,
            R.mipmap.img_04,
            R.mipmap.img_05,
            R.mipmap.img_06,
            R.mipmap.img_07,
            R.mipmap.img_08,
            R.mipmap.img_09,
            R.mipmap.img_010,
            R.mipmap.img_11,
            R.mipmap.img_01,
            R.mipmap.img_02,
            R.mipmap.img_03,
            R.mipmap.img_04,
            R.mipmap.img_05,
            R.mipmap.img_06,
            R.mipmap.img_07,
            R.mipmap.img_08,
            R.mipmap.img_09,
            R.mipmap.img_010,
            R.mipmap.img_11
    };

}
